"""Detection signals for Provenance Guard.

Signal 1 (llm_signal): semantic/holistic read of the text via Groq.
Signal 2 (stylometric_signal): pure-Python structural/statistical heuristics.

The two signals are independent: one reasons about meaning, the other about
surface statistics. See planning.md for the full rationale and blind spots.
"""
import json
import os
import re
import statistics

from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
GROQ_MODEL = "llama-3.3-70b-versatile"

_groq_client = None
if GROQ_API_KEY:
    from groq import Groq
    _groq_client = Groq(api_key=GROQ_API_KEY)


LLM_PROMPT = """You are a text-provenance analyst. Read the passage below and \
judge whether it was most likely written by a human or generated by an AI \
language model.

Respond with ONLY a JSON object, no other text, in this exact shape:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

ai_probability = 1.0 means you are certain it is AI-generated.
ai_probability = 0.0 means you are certain a human wrote it.
ai_probability = 0.5 means you genuinely cannot tell.

Passage:
\"\"\"{text}\"\"\"
"""


def llm_signal(text):
    """Signal 1: LLM-based semantic classification.

    Returns (score: float in [0,1], details: dict).
    Falls back to a deterministic keyword heuristic if no Groq key is
    configured or the API call fails, so the pipeline stays functional.
    """
    if _groq_client is not None:
        try:
            resp = _groq_client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
                temperature=0,
                max_tokens=200,
            )
            raw = resp.choices[0].message.content.strip()
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            parsed = json.loads(match.group(0) if match else raw)
            score = float(parsed.get("ai_probability", 0.5))
            score = max(0.0, min(1.0, score))
            return score, {
                "source": "groq_llama-3.3-70b-versatile",
                "reasoning": parsed.get("reasoning", ""),
            }
        except Exception as exc:  # network/parsing failure -> fallback
            return _llm_fallback(text, error=str(exc))
    return _llm_fallback(text, error="no GROQ_API_KEY configured")


_AI_MARKERS = [
    "furthermore", "moreover", "it is important to note", "in conclusion",
    "on the other hand", "overall", "additionally", "as previously mentioned",
    "in summary", "it is worth noting", "stakeholders", "paradigm",
]


def _llm_fallback(text, error):
    """Deterministic stand-in used only when Groq is unavailable, so the
    pipeline still runs end-to-end. Not a substitute for the real signal."""
    lowered = text.lower()
    hits = sum(1 for marker in _AI_MARKERS if marker in lowered)
    word_count = max(len(text.split()), 1)
    density = hits / word_count
    score = max(0.0, min(1.0, 0.4 + density * 15))
    return score, {
        "source": "fallback_heuristic",
        "reasoning": f"Groq unavailable ({error}); used AI-marker keyword density as a stand-in.",
    }


_SENTENCE_SPLIT_RE = re.compile(r"[.!?]+(?:\s+|$)")
_WORD_RE = re.compile(r"[A-Za-z']+")


def stylometric_signal(text):
    """Signal 2: pure-Python stylometric heuristics.

    Combines three normalized sub-metrics into a single 0-1 "reads AI-like"
    score. Returns (score: float in [0,1], details: dict of raw metrics).
    """
    sentences = [s.strip() for s in _SENTENCE_SPLIT_RE.split(text) if s.strip()]
    words = _WORD_RE.findall(text)
    word_count = max(len(words), 1)

    # 1. Sentence-length variance ("burstiness"). Low variance -> AI-like.
    sentence_lengths = [len(_WORD_RE.findall(s)) for s in sentences] or [word_count]
    variance = statistics.pvariance(sentence_lengths) if len(sentence_lengths) > 1 else 0.0
    variance_norm = min(variance / 40.0, 1.0)
    uniformity_score = 1.0 - variance_norm

    # 2. Type-token ratio (vocabulary diversity). Low diversity -> AI-like.
    lowered_words = [w.lower() for w in words]
    ttr = len(set(lowered_words)) / word_count
    ttr_ai_score = 1.0 - min(ttr / 0.8, 1.0)

    # 3. Informal/expressive punctuation density. Low density -> AI-like.
    informal_hits = len(re.findall(r"!{1,}|\?{2,}|\.{3,}", text))
    informal_density = informal_hits / word_count
    informal_ai_score = 1.0 - min(informal_density / 0.05, 1.0)

    score = (uniformity_score + ttr_ai_score + informal_ai_score) / 3.0
    score = max(0.0, min(1.0, score))

    return score, {
        "sentence_count": len(sentences),
        "sentence_length_variance": round(variance, 2),
        "uniformity_score": round(uniformity_score, 3),
        "type_token_ratio": round(ttr, 3),
        "ttr_ai_score": round(ttr_ai_score, 3),
        "informal_punct_density": round(informal_density, 4),
        "informal_ai_score": round(informal_ai_score, 3),
    }
